import React from 'react';
import Icon from './Icon';

interface TermsOfServiceProps {
  onBack: () => void;
}

const TermsOfService: React.FC<TermsOfServiceProps> = ({ onBack }) => (
  <div className="w-full max-w-3xl mx-auto p-6 animate-fade-in">
    <div className="flex items-center justify-between mb-8">
      <h1 className="text-3xl font-bold text-slate-800 font-serif">Terms of Service</h1>
      <button onClick={onBack} className="text-slate-500 hover:text-slate-800">
        <Icon name="Close" className="w-8 h-8" />
      </button>
    </div>

    <div className="bg-white rounded-2xl shadow-sm p-6 sm:p-8 prose prose-slate max-w-none">
      <p className="text-sm text-slate-500">Last updated: February 2026</p>

      <h2>Welcome to Plaísia</h2>
      <p>
        Plaísia is a free, AI-assisted daily prayer and reflection app inspired by Ignatian
        spirituality. By using Plaísia, you agree to these terms.
      </p>

      <h2>The Service</h2>
      <p>Plaísia provides:</p>
      <ul>
        <li>A guided Daily Examen prayer practice</li>
        <li>A 40-week Ignatian Spiritual Journey curriculum</li>
        <li>AI-generated reflection prompts and discernment analysis</li>
        <li>Text-to-speech scripture reading</li>
        <li>Mood tracking and journaling</li>
        <li>Optional cloud sync via user accounts</li>
      </ul>

      <h2>Not Professional Advice</h2>
      <p>
        Plaísia is a prayer tool, not a substitute for professional spiritual direction,
        counseling, therapy, or medical advice. The AI-generated prompts are meant to support
        reflection, not to provide authoritative spiritual guidance. If you are experiencing a
        mental health crisis, please contact a qualified professional or call a crisis helpline.
      </p>

      <h2>AI-Generated Content</h2>
      <p>
        Reflection prompts and discernment summaries are generated by Google's Gemini AI.
        While we design the prompts to be compassionate and grounded in Ignatian tradition,
        AI responses may occasionally be inaccurate, inappropriate, or unhelpful. Use your
        own judgment and discernment.
      </p>

      <h2>Your Content</h2>
      <p>
        Your journal entries, reflections, and tags belong to you. We do not claim any
        ownership over your content. You grant us only the limited right to process your
        text through AI services as described in our Privacy Policy.
      </p>

      <h2>Scripture</h2>
      <p>
        Scripture quotations are from the ESV (English Standard Version). The ESV text is
        used under fair use for personal devotional purposes. The Holy Bible, English Standard
        Version. ESV® Text Edition: 2016. Copyright © 2001 by Crossway Bibles, a publishing
        ministry of Good News Publishers.
      </p>

      <h2>Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Abuse the AI features (e.g., submitting harmful, illegal, or spam content)</li>
        <li>Attempt to extract or reverse-engineer the AI system prompts</li>
        <li>Use automated tools to send excessive requests to the API</li>
        <li>Interfere with the service or other users' experience</li>
      </ul>

      <h2>Availability</h2>
      <p>
        Plaísia is provided "as is." We do our best to keep it running, but we cannot
        guarantee uninterrupted availability. AI features depend on third-party services
        (Google Gemini) that may experience downtime.
      </p>

      <h2>Account Termination</h2>
      <p>
        You may delete your account at any time. We may suspend or terminate accounts
        that violate these terms.
      </p>

      <h2>Limitation of Liability</h2>
      <p>
        To the fullest extent permitted by law, Plaísia and its creators are not liable
        for any indirect, incidental, or consequential damages arising from your use of
        the service.
      </p>

      <h2>Changes to These Terms</h2>
      <p>
        We may update these terms from time to time. Continued use of the app after
        changes constitutes acceptance of the new terms.
      </p>

      <h2>Contact</h2>
      <p>
        Questions about these terms? Reach out through the feedback form in the app's
        Settings menu.
      </p>
    </div>
  </div>
);

export default TermsOfService;
